ALTER TABLE transactions ADD COLUMN IF NOT EXISTS rev BIGINT NOT NULL DEFAULT 1;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS base_rev BIGINT NOT NULL DEFAULT 1;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS client_id UUID;

CREATE INDEX IF NOT EXISTS idx_transactions_rev ON transactions(rev);
CREATE INDEX IF NOT EXISTS idx_transactions_deleted ON transactions(deleted);
